### ISSUE TITLE
 open /run/config/pki/apiserver-kubelet-client.crt: no such file or directory

### ISSUE THREAD

**Issue by hazcod** [cockroachdb/helm-charts#169]
Any idea what I'm doing wrong?

```yaml
cockroachdb:
  tls:
    enabled: true
  statefulset:
    replicas: 1
    resources:
      limits:
        memory: "4Gi"
      requests:
        memory: "2Gi"
  conf:
    single-node: "yes"
    cache: "1024Mi"
    max-sql-memory: "1024Mi"
```

Logs:
```
Namespace
iron-backend-dev
Pod
temporal-cockroachdb-0
Container
db
Search...
Failed to load logs: Get "https://10.99.0.4:10250/containerLogs/iron-backend-dev/temporal-cockroachdb-0/db?tailLines=502&timestamps=true": open /run/config/pki/apiserver-kubelet-client.crt: no such file or director
```
