### ISSUE TITLE
Certificate rotation cronjob times out on non-configurable pod readiness timeout

### ISSUE THREAD

**Issue by JorritSalverda** [cockroachdb/helm-charts#190]
Our connection to a cockroachdb cluster started failing with `remote error: tls: bad certificate`. Turned out that the `rotate-self-signer-client` cronjob had failed to renew all secrets.

The cronjob looks like:

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
    meta.helm.sh/release-name: estafette-ci
    meta.helm.sh/release-namespace: estafette-ci
  labels:
    app.kubernetes.io/instance: estafette-ci
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: db
    helm.sh/chart: db-6.1.2
  name: estafette-ci-db-rotate-self-signer-client
  namespace: estafette-ci
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      backoffLimit: 1
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - rotate
            - --ca-duration=43800h
            - --ca-expiry=648h
            - --client
            - --client-duration=672h
            - --client-expiry=48h
            - --node
            - --node-duration=8760h
            - --node-expiry=168h
            - --node-client-cron="0 0 */26 * *"
            - --readiness-wait=90s
            env:
            - name: STATEFULSET_NAME
              value: estafette-ci-db
            - name: NAMESPACE
              value: estafette-ci
            - name: CLUSTER_DOMAIN
              value: cluster.local
            image: gcr.io/cockroachlabs-helm-charts/cockroach-self-signer-cert:1.1
            imagePullPolicy: IfNotPresent
            name: cert-rotate-job
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: estafette-ci-db-rotate-self-signer
          serviceAccountName: estafette-ci-db-rotate-self-signer
          terminationGracePeriodSeconds: 30
  schedule: 0 0 */26 * *
  successfulJobsHistoryLimit: 3
  suspend: false
status:
  lastScheduleTime: "2021-10-01T00:00:00Z"
```

When running it seems to fail to verify pod readiness of the statefulset pods with the following panic:

```
time="2021-10-07T08:29:13Z" level=info msg="CA secret [estafette-ci-db-ca-secret] is found in ready state, skipping CA generation"
time="2021-10-07T08:29:13Z" level=info msg="Node Certificate: Failed to verify expiry date due to invalid cron, rotating certificate"
time="2021-10-07T08:29:13Z" level=info msg="Generating node certificate"
time="2021-10-07T08:29:13Z" level=info msg="Generated and saved node key and certificate in secret [estafette-ci-db-node-secret]"
time="2021-10-07T08:29:13Z" level=info msg="Performing rolling update after certificate rotation"
time="2021-10-07T08:29:18Z" level=info msg="Pod estafette-ci-db-0 in ready state now"
time="2021-10-07T08:29:18Z" level=info msg="waiting for 30s duration for pod readiness"
time="2021-10-07T08:29:53Z" level=info msg="Pod estafette-ci-db-1 in ready state now"
time="2021-10-07T08:29:53Z" level=info msg="waiting for 30s duration for pod readiness"

panic:  error Generating Node Certificate: Pod estafette-ci-db-2 not in ready state

goroutine 1 [running]:
log.Panic(0xc00042dc88, 0x1, 0x1)
	/usr/local/go/src/log/log.go:351 +0xae
github.com/cockroachdb/helm-charts/cmd/self-signer.rotate(0x2111240, 0xc000123d60, 0x0, 0xa)
	/cmd/self-signer/rotate.go:90 +0x37b
github.com/spf13/cobra.(*Command).execute(0x2111240, 0xc000123ae0, 0xa, 0xa, 0x2111240, 0xc000123ae0)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2110fc0, 0x445caa, 0x20a1e20, 0xc000062778)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/cockroachdb/helm-charts/cmd/self-signer.Execute()
	/cmd/self-signer/root.go:50 +0x31
main.main()
	/cmd/main.go:22 +0x25
```

I tried using a longer readiness time of 90s, but it seems to be just a wait time between pods being ready, not the actual time it waits for a pod to be ready since it's hardcoded at https://github.com/cockroachdb/helm-charts/blob/c7b98361cf87eb161d13c04611e0c66d7705a278/pkg/kube/helpers.go#L140.

Would be nice to make that configurable, I guess it takes longer than 2 minutes in our case.

Since the node certificate actually was renewed and all cluster nodes refreshed the cluster itself was fine. We just had to create a job with the following arguments to ensure the client certificate also got renewed:

```yaml
          args:
            - rotate
            - --ca-duration=43800h
            - --ca-expiry=648h
            - --client
            - --client-duration=672h
            - --client-expiry=48h
```

Perhaps sensible to do client certificate renewal first, then the node certificate renewal since it's more frail to finish. Or split into separate cronjobs, one for node certs, one for client certs.
