### ISSUE TITLE
server,ui: infinite HTTP redirect when accessing UI for secure cluster behind nginx-ingress in k8s

### ISSUE THREAD

**Issue by sergeyshaykhullin** [cockroachdb/helm-charts#228]
**Describe the problem**
I am getting  `too many redirects` when trying to access secure cockroachdb cluster behind ingress-nginx using [helm chart](https://hub.helm.sh/charts/stable/cockroachdb).

Please describe the issue you observed, and any steps we can take to reproduce it:

It is happening because tls.enabled == secure cluster with tls termination.
Same thing i got with [argo cd](https://github.com/argoproj/argo-cd/issues/2953#issuecomment-602898868) and solved using --insecure flag (Insecure - just about tls termination)
So i have to use insecure cluster behind ingress (losing auth screen, users with passwords etc) or secure cluster without ingress inside k8s (And i have to manage certificates, use not 80 and 443 ports, it's painful)

**To Reproduce**

1. Setup basic k8s cluster
2. Setup nginx-ingress, cert-manager
3. Setup secure cockroachdb cluster
4. Create k8s Ingress for cockroachdb service
5. Try to access admin panel

**Expected behavior**
I can disable tls termination in web ui, but don't lose security cluster benefits

**Additional data / screenshots**
- I am using helm charts:
  - https://hub.helm.sh/charts/stable/cockroachdb
  - https://hub.helm.sh/charts/stable/nginx-ingress
  - https://hub.helm.sh/charts/jetstack/cert-manager

**Environment:**
 - CockroachDB version 20.1
 - Server OS: Debian 10

Jira issue: CRDB-4219

**Comment by pseudomuto** [comment]
While starting to take a look into this, I was able to reproduce this issue using the following steps. I figured these steps could be helpful if anyone else is interested in verifying the issue or playing around with different config settings.

Start by creating a few files we'll use for getting everything set up.

<details>
<summary>Support files for testing</summary>

```yaml
# hack/issuer.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: expiry@example.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
     - http01:
         ingress:
           class: nginx
```

```yaml
# hack/values.yaml
ingress:
  enabled: true
  annotations:
    cert-manager.io/issuer: letsencrypt-staging
    kubernetes.io/ingress.class: nginx
  hosts:
    - crdb.example.com
  tls:
    - hosts: [crdb.example.com]
      secretName: crdb-example-com-tls
```

```bash
# hack/exec (don't forget to chmod +x this file)
#!/usr/bin/env bash
set -euo pipefail

CLUSTER="${CLUSTER:-"$(whoami)-test"}"
REGION="${REGION:-us-east1}"

main() {
  case "${1:-}" in
    create-cluster) create_cluster;;
    delete-cluster) delete_cluster;;
    apply)
      # ensure we've got the necessary binaries
      make bin/helm bin/kubectl
      install_cert_manager
      install_ingress_nginx
      install_chart;;
    *)
      echo "Unknown command '${1:-}'." 1>&2
      echo "Usage: ${0} <command>"
      echo "  commands:"
      echo "    create-cluster    create a GKE cluster for testing"
      echo "    delete-cluster    delete the GKE cluster"
      echo "    apply             (idempotently) install cert-manager, ingress-nginx, and this chart"
      exit 1;;
  esac
}

create_cluster() {
  println "Creating GKE cluster ${CLUSTER}..."
  gcloud container clusters create "${CLUSTER}" --region "${REGION}" --num-nodes 1
}

delete_cluster() {
  println "Deleting GKE cluster ${CLUSTER}..."
  gcloud container clusters delete "${CLUSTER}" --region "${REGION}"
}

install_chart() {
  println "Installing local cockroachdb chart..."
  bin/helm upgrade -f hack/values.yaml --install crdb ./cockroachdb
}

install_ingress_nginx() {
  println "Installing ingress-nginx..."
  bin/helm upgrade --install ingress-nginx ingress-nginx \
    --repo https://kubernetes.github.io/ingress-nginx \
    --namespace ingress-nginx --create-namespace

  println "Waiting for ingress controller to be available..."
 bin/kubectl wait --namespace ingress-nginx \
    --for=condition=ready pod \
    --selector=app.kubernetes.io/component=controller \
    --timeout=90s
}

install_cert_manager() {
  println "Installing cert-manager..."
  bin/helm upgrade --install cert-manager cert-manager \
    --repo https://charts.jetstack.io \
    --namespace cert-manager \
    --create-namespace \
    --set installCRDs=true

  println "Creating letencrypt issuer..."
  bin/kubectl apply -f hack/issuer.yaml
}

println() {
  echo -e "\033[36m${1}\033[0m"
}

main "$@"
```
</details>

> You'll need a working K8s cluster. If you don't have one you can run `hack/exec create-cluster` to create a GKE cluster. This assumes you've got `gcloud` installed and configured with an account that can create/manage GKE clusters. The cluster can be deleted with `hack/exec delete-cluster` when you're done.

Install cert-manager, ingress-nginx, and the cockroachdb chart by running `hack/exec apply`. This can be re-run as needed (idempotent) which can be useful if you change the values or issuer files and want to upgrade the charts.

With everything set up, get a hold of the external IP for the ingress object:

```
bin/kubectl get ing crdb-cockroachdb-ingress -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
```

cURL the ingress and verify you get an error about maximum redirects reached:

```
curl -kL --resolve crdb.example.com:443:<LB_IP_FROM_ABOVE> https://crdb.example.com
> curl: (47) Maximum (50) redirects followed
```

**Comment by dhartunian** [comment]
I think this behavior is due to this snippet below which redirects *all* traffic on the HTTP port to HTTPS except for the healthcheck. @pseudomuto I'm guessing `/health` resolves correctly in your example.

Maybe what we should do is inspect `X-Forwarded-Proto` and disable redirect when it's set to `https`. What do you think @udnay @pseudomuto ? (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto, I assume nginx sets this)

https://github.com/cockroachdb/cockroach/blob/946b9c545127557bc8a6e1e05905a85db5095e7f/pkg/server/server_http.go#L222-L238

**Comment by nv30** [comment]
Is there any workaround for this problem?

**Comment by Djankaa** [comment]
Any progress here?

**Comment by HcgRandon** [comment]
Waiting to see a solution for this? A lot of people use ingresses...

**Comment by HcgRandon** [comment]
Heads up for others; If your ingress is nginx based you can add the `nginx.ingress.kubernetes.io/backend-protocol: HTTPS` annotation to the ingress definition and this will fix the issue.

**Comment by Djankaa** [comment]
@HcgRandon 
Works perfectly! Thank you!

**Comment by github-sys-admin** [comment]
NOPE STILL DOESNT WORK 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
    meta.helm.sh/release-name: cockroachdb
    meta.helm.sh/release-namespace: whocares-prod
    traefik.ingress.kubernetes.io/service.serversscheme: https
  labels:
    app.kubernetes.io/instance: cockroachdb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cockroachdb
    helm.sh/chart: cockroachdb-7.0.3
  name: cockroachdb-ingress
  namespace: whocares-prod
spec:
  rules:
  - host: go.sodomize.your.self
    http:
      paths:
      - backend:
          service:
            name: cockroachdb-public
            port:
              number: 8080
        path: /
        pathType: Prefix
status:
  loadBalancer: {}

```

**Comment by rajavarapusaiprasanth-hpe** [comment]
has anyone tried using path based routing instead of host based routing? I am facing issue on `/api/v2/sql` and `/uiconfig` when using a different path instead of `/`

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: cockroachdb-ingress
  namespace: cockroach
spec:
  rules:
  - host: shared.host.name
    http:
      paths:
      - backend:
          service:
            name: croach-cockroachdb-public
            port:
              number: 8080
        path: /cockroach(/|$)(.*)
        pathType: ImplementationSpecific
```
