### ISSUE TITLE
install with flux not working

### ISSUE THREAD

**Issue by vincentserpoul** [cockroachdb/helm-charts#234]
Easy to reproduce:

1. On any cluster, install [flux](https://fluxcd.io)
2. deploy crdb using flux helm CRDs

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: cockroachdb
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cockroachdb
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.cockroachdb.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cockroachdb
  namespace: cockroachdb
spec:
  interval: 1m
  chart:
    spec:
      chart: "cockroachdb"
      version: ">=7.0.1"
      sourceRef:
        kind: HelmRepository
        name: cockroachdb
        namespace: flux-system
      interval: 1m
  targetNamespace: cockroachdb
```

I am not sure if it's on flux or cockroachdb, but it's worth creating an issue to centralize the fix.

I opened an issue on flux side [here](https://github.com/fluxcd/flux2/issues/2563)

**Comment by davidwding** [comment]
Hello, I saw on the related flux issue that "Direct healm install works." - to clarify, you mean you got CockroachDB working on helm without flux? If so, this seems like an issue on the flux side. I saw that they're providing advice over there, but let us know if there's something on our side that we need to look at.

**Comment by vincentserpoul** [comment]
As mentioned on the flux side of things, I could reproduce the error with and without flux, so I guess this now happens here.

**Comment by vincentserpoul** [comment]
not using --wait anymore, I still need to helm install once, uninstall and then reinstall
I guess it's the time needed for the operator to come up?

Is it better to install the operator CRD and then the helm install? Or is there a proper way?

**Comment by davidwding** [comment]
I would recommend following the steps specified in our Helm chart deployment docs: https://www.cockroachlabs.com/docs/stable/deploy-cockroachdb-with-kubernetes.html?filters=helm

**Comment by vincentserpoul** [comment]
That's what I do: 

```
helm install my-release --values {custom-values}.yaml cockroachdb/cockroachdb
```

Right now, I need to run it once, uninstall and then reinstall for it to work.

**Comment by udnay** [comment]
> Is it better to install the operator CRD and then the helm install? Or is there a proper way?

Are you trying to use the public operator *and* the helm chart? They functionally do the same thing. Does `operator` mean something different in this context?

**Comment by vincentserpoul** [comment]
Sorry, this sentence might have been confusing, I was just throwing an idea.

I am simply installing the helm chart as per the docs.

**Comment by daniel-crlabs** [comment]
So we understand this correctly, you stated the following:

>I am simply installing the helm chart as per the docs.
It is pretty straightforward to reproduce: using [k3d](https://k3d.io/v5.3.0/%5D) and helm (that is what I am using, it does not mean it is specific to this platform).

I was not able to reproduce this problem. Let's go ahead and try to simplify the process and take flux out of the equation. Once you are able to install via helm alone (as shown below), we can try and figure out what might be happening with flux.
I was able to install CockroachDB using the helm charts without any issues. I am not using k3d, so maybe this is the problem you might be running into, I'm not sure as I have not used this to test it. 
With that being said, I was able to deploy CockroachDB using the helm charts to a lab running on 3 VMs, here is the entire process. I created my own custom dynamic volume provisioner (maybe you are missing this as well, since these mini k8s deployments might not have all necessary functionality you might expect) and for this test did not use certs. Please try this as well, so we can determine if the cert part of the process might be missing something or not.

Steps shown below:

Add helm repo:

```
[LAB] root@lab-kub01: helm # helm repo add cockroachdb https://charts.cockroachdb.com/
"cockroachdb" already exists with the same configuration, skipping
```

Update repo:

```
[LAB] root@lab-kub01: helm # helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "cockroachdb" chart repository
Update Complete. ⎈Happy Helming!⎈
```

Create storage class and dynamic volume provisioner (this might be only necessary in my lab, as I'm running on vagrant vms):

```
[LAB] root@lab-kub01: helm # kubectl apply -f sc.yml
serviceaccount/glfs-provisioner created
clusterrole.rbac.authorization.k8s.io/glfs-provisioner-runner unchanged
clusterrolebinding.rbac.authorization.k8s.io/run-glfs-provisioner configured
storageclass.storage.k8s.io/cockroach-helm-dynamic created
```

Deploy helm chart:

```
[LAB] root@lab-kub01: helm # helm install cockroachdb --values custom-values.yml --set image.tag=v21.2.7 cockroachdb/cockroachdb
W0324 14:18:14.823945   11225 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0324 14:18:14.829262   11225 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W0324 14:18:15.001830   11225 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0324 14:18:15.067797   11225 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
NAME: cockroachdb
LAST DEPLOYED: Thu Mar 24 14:18:14 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
CockroachDB can be accessed via port 26257 at the
following DNS name from within your cluster:

cockroachdb-public.default.svc.cluster.local

Because CockroachDB supports the PostgreSQL wire protocol, you can connect to
the cluster using any available PostgreSQL client.

For example, you can open up a SQL shell to the cluster by running:

    kubectl run -it --rm cockroach-client \
        --image=cockroachdb/cockroach \
        --restart=Never \
        --command -- \
        ./cockroach sql --insecure --host=cockroachdb-public.default

From there, you can interact with the SQL shell as you would any other SQL
shell, confident that any data you write will be safe and available even if
parts of your cluster fail.

Finally, to open up the CockroachDB admin UI, you can port-forward from your
local machine into one of the instances in the cluster:

    kubectl port-forward cockroachdb-0 8080

Then you can access the admin UI at http://localhost:8080/ in your web browser.

For more information on using CockroachDB, please see the project's docs at:
https://www.cockroachlabs.com/docs/
```

Pod status:

```
[LAB] root@lab-kub01: helm # kubectl get pods
NAME                     READY   STATUS      RESTARTS   AGE
cockroachdb-0            1/1     Running     0          88s
cockroachdb-1            1/1     Running     0          88s
cockroachdb-2            1/1     Running     0          88s
cockroachdb-init-2gvlk   0/1     Completed   0          88s
```

Used files for your reference:

storage class config, service account and roles:

`sc.yml`

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: glfs-provisioner
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: glfs-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events", "pods/exec"]
    verbs: ["create", "update", "patch"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-glfs-provisioner
subjects:
  - kind: ServiceAccount
    name: glfs-provisioner
    namespace: default
# update namespace above to your namespace in order to make this work
roleRef:
  kind: ClusterRole
  name: glfs-provisioner-runner
  apiGroup: rbac.authorization.k8s.io


---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cockroach-helm-dynamic
  annotations:
    storageclass.kubernetes.io/is-default-class: "true" # This makes this storageclass the default
provisioner: kubernetes.io/glusterfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  resturl: "http://lab-kub01:8080"
  restauthenabled: "false"
```

`custom-values.yml`

```
statefulset:
  customLivenessProbe: {}
  customReadinessProbe: {}
  resources:
    limits:
      cpu: "0.5"
      memory: "256Mi"
    requests:
      cpu: "0.5"
      memory: "256Mi"
tls:
  enabled: false
conf:
  log:
    enabled: true
    config:
      sinks:
        stderr:
          channels: all
          filter: INFO
          redact: false
          redactable: false
          exit-on-error: true
      capture-stray-errors:
        enable: true
        max-group-size: 100MiB
  logtostderr: INFO
storage:
  persistentVolume:
    enabled: true
    size: 256Mi
    storageClass: "cockroach-helm-dynamic"
```

**Comment by vincentserpoul** [comment]
I think I will isolate the culprit later on and create a new issue if needed, as right now it's becoming quite confusing.

The bottom line if you are reading this and have an issue with flux:

add this to your HelmRelease:

```yaml
spec:
  interval: 1m
  install:
    disableWait: true
```

thanks a lot for your reactivity @davidwding  @udnay  @daniel-crlabs
