### ISSUE TITLE
Bug: ServiceMonitor should use https instead of http

### ISSUE THREAD

**Issue by incubator4** [cockroachdb/helm-charts#386]
current `servicemonitor` resources without option scheme, it can only be used for insecure clusters, example like this.

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cockroachdb
spec:
  endpoints:
    - interval: 10s
      path: /_status/vars
      port: http
      # without scheme: https
      tlsConfig:
        ca:
          secret:
            key: ca.crt
            name: cockroachdb-node
        cert:
          secret:
            key: tls.crt
            name: cockroachdb-node
        insecureSkipVerify: true
        keySecret:
          key: tls.key
          name: cockroachdb-node
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/component: cockroachdb
      app.kubernetes.io/instance: cockroachdb
      app.kubernetes.io/name: cockroachdb
```
