### ISSUE TITLE
Are there any use cases for auto-init by `init.provisioning.enabled=true`

### ISSUE THREAD

**Issue by incubator4** [cockroachdb/helm-charts#389]
example and minimum values.yaml
```yaml
init:
  provisioning:
    enabled: true
```
It should create a cockroachdb cluster and auto-into with job
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app.kubernetes.io/component: init
    app.kubernetes.io/instance: cockroachdb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cockroachdb
    helm.sh/chart: cockroachdb-12.0.5
  name: cockroachdb-init
  namespace: default
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: init
        app.kubernetes.io/instance: cockroachdb
        app.kubernetes.io/name: cockroachdb
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - |-
          initCluster() {

            while true; do
              local output=$(
                set -x;

                /cockroach/cockroach init \
                  --certs-dir=/cockroach-certs/ \
                  --host=cockroachdb-0.cockroachdb:26257 \
              2>&1);

              local exitCode="$?";
              echo $output;

              if [[ "$output" =~ .*"Cluster successfully initialized".* || "$output" =~ .*"cluster has already been initialized".* ]]; then
                break;
              fi

              echo "Cluster is not ready to be initialized, retrying in 5 seconds"
              sleep 5;
            done
          }
          initCluster; provisionCluster() {

            while true; do
              /cockroach/cockroach sql \
                --certs-dir=/cockroach-certs/ \
                --host=cockroachdb-0.cockroachdb:26257 \
                --execute="
                "
              &>/dev/null;

              local exitCode="$?";

              if [[ "$exitCode" -eq "0" ]]
                then break;
              fi

              sleep 5;
            done

            echo "Provisioning completed successfully";
          }
          provisionCluster;
        env: null
        image: cockroachdb/cockroach:v23.2.5
        imagePullPolicy: IfNotPresent
        name: cluster-init
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /cockroach-certs/
          name: client-certs
      initContainers:
      - command:
        - /bin/sh
        - -c
        - cp -f /certs/* /cockroach-certs/; chmod 0400 /cockroach-certs/*.key
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: busybox
        imagePullPolicy: IfNotPresent
        name: copy-certs
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /cockroach-certs/
          name: client-certs
        - mountPath: /certs/
          name: certs-secret
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: cockroachdb
      terminationGracePeriodSeconds: 300
      volumes:
      - emptyDir: {}
        name: client-certs
      - name: certs-secret
        projected:
          sources:
          - secret:
              items:
              - key: ca.crt
                mode: 256
                path: ca.crt
              - key: tls.crt
                mode: 256
                path: client.root.crt
              - key: tls.key
                mode: 256
                path: client.root.key
              name: cockroachdb-client-secret
```

Due to annotations `helm.sh/hook: post-install,post-upgrade` , it must be triggered after the cluster is ready, but cluster must init before ready,it seems to be stuck in a deadlock, or maybe I configured the wrong values.yaml, does anyone have experience or ideas about this?
