### ISSUE TITLE
Bug: helm lint|template causes unexpected error "CA secret is not present in the release namespace"

### ISSUE THREAD

**Issue by Kradepon** [cockroachdb/helm-charts#394]
Chart version: 13.0.0
helm version: v3.9.1

My `values.yaml`
```yaml annotate
cockroachdb:
  image:
    repository: cockroachdb/cockroach
    tag: v24.1.0
  conf:
    port: 26257
    cache: 25%
    max-sql-memory: 25%
  tls:
    enabled: true
    certs:
      selfSigner:
        enabled: true
        caProvided: true
        caSecret: cockroachdb-ca
```

In the charts [helm template](https://github.com/cockroachdb/helm-charts/blob/58c2e86e49b380d763d4e2cb58d729796af4592e/cockroachdb/templates/_helpers.tpl#L200)

```helm annotate
{{/*
Validate that if caProvided is true, then the caSecret must not be empty and secret must be present in the namespace.
*/}}
{{- define "cockroachdb.tls.certs.selfSigner.caProvidedValidation" -}}
{{- if .Values.tls.certs.selfSigner.caProvided -}}
{{- if eq "" .Values.tls.certs.selfSigner.caSecret -}}
    {{ fail "CA secret can't be empty if caProvided is set to true" }}
{{- else -}}
    {{- if not (lookup "v1" "Secret" .Release.Namespace .Values.tls.certs.selfSigner.caSecret) }}
        {{ fail "CA secret is not present in the release namespace" }}
    {{- end }}
{{- end -}}
{{- end -}}
{{- end -}}
```

the line `if not (lookup "v1" "Secret" .Release.Namespace .Values.tls.certs.selfSigner.caSecret)` causes any attempt to `helm lint` or `helm template` to fail with the appropriate error, although the secret is present in the release namespace. Is there any way to skip this validation or how is this supposed to work?
