### ISSUE TITLE
grpc internal port should be configured from one place only 

### ISSUE THREAD

**Issue by prafull01** [cockroachdb/helm-charts#417]
We recommend separating internal grpc port from sql port for large scale clusters. 

In Helm chart in order to change internal grpc port we need to configure it at two places:
```
service:
  ports:
    # You can set a different external and internal gRPC ports and their name.
    grpc:
      external:
        port: 26257
        name: grpc
      # If the port number is different than `external.port`, then it will be
      # named as `internal.name` in Service.
      internal:
        port: 26257
        # If using Istio set it to `cockroach`.
        name: grpc-internal
    http:
      port: 8080 
      name: http
```

Also the same port is defined:
```
conf:
  port: 26257
  http-port: 8080
```

Ideally this configuration at one place so that user doesn't have to change at two place.

--port & --http-port has been depreciated, but they’re still used in Helm chart, we should deprecate those port in helm chart.
