### ISSUE TITLE
Add the ability to define a custom init container to run in addition to the current one for certs

### ISSUE THREAD

**Issue by udnay** [cockroachdb/helm-charts#422]
Allow a second container to be run in addition to the cert init container for stateful set pods.

**Comment by udnay** [comment]
@prafull01 can you take a look at this?  The idea is to allow a pod to check and write locality metadata to a shared volume mount. Something like
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: metadata-fetcher
spec:
  volumes:
    - name: metadata-volume
      emptyDir: {}

  initContainers:
    - name: fetch-metadata
      image: busybox:latest
      command:
        - sh
        - -c
        - |
          curl -s -H "Metadata:true" --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01" | jq '.' > /metadata/instance_metadata.json
      volumeMounts:
        - name: metadata-volume
          mountPath: /metadata
...
```
