### ISSUE TITLE
Init job as a helm hook

### ISSUE THREAD

**Issue by sergeyshaykhullin** [cockroachdb/helm-charts#45]
For now init job is part of chart, deploys once and constantly available in a cluster

Main problem is to upgrade cluster, job is immutable and failing on crdb version upgrade. Workaround is to delete init job and helm upgrade again

I think that init job should be a helm hook like this (**IF INIT JOB IS IDEMPOTENT** and i think it is)

```yaml
annotations:
  helm.sh/hook: post-install,post-upgrade
  # This will delete job after succeeded
  helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
```

Minio implementation of buckets provisioning reference: https://github.com/minio/charts/blob/master/minio/templates/post-install-create-bucket-job.yaml
