### ISSUE TITLE
Add backup cron job support

### ISSUE THREAD

**Issue by sergeyshaykhullin** [cockroachdb/helm-charts#5]
Add backup support like: https://github.com/zalando/postgres-operator/blob/master/docs/reference/cluster_manifest.md#top-level-parameters

```yaml
backup:
  schedule: 0 1 * * *
  endpoint: 
  bucket: 
  accessKey: 
  secretKey: 
```
