### ISSUE TITLE
User creation during provisioning step fails

### ISSUE THREAD

**Issue by heytrav** [cockroachdb/helm-charts#509]
When using the `init.provisioning.enabled: true` and attempting to create a user for the database, the init script always fails with an error message:
```
cluster-init ++ /cockroach/cockroach init --certs-dir=/cockroach-certs/ --cluster-name=dev --host=cockroachdb-0.cockroachdb:26257
cluster-init E250502 01:51:04.786205 29 2@rpc/peer.go:679 [rnode=?,raddr=cockroachdb-0.cockroachdb:26257,class=system,rpc] 1 failed connection attempt (last connected 0s ago): grpc:
cluster-init ERROR: empty passwords are not permitted
cluster-init Failed running "sql"
cluster-init Provisioning completed successfully
```

My helm values config contains the following:
```
init:
  provisioning:
    enabled: true
    users:
      - name: devuser
         password: devpassword
         options:
           - LOGIN
    databases:
      - name: crdb
        owners:
          - devuser

```

I'm not really sure why it says `empty passwords` but I can't find any explanation for what is expected in the password field.

**Comment by heytrav** [comment]
It looks to me like the [code for creating the password](https://github.com/cockroachdb/helm-charts/blob/master/cockroachdb/templates/job.init.yaml) is meant to use the `$user.name` to create the [environment variable](https://github.com/cockroachdb/helm-charts/blob/d445867d5e180d3e6cecf8b48684bdc73f0e64e0/cockroachdb/templates/job.init.yaml#L236).

Instead however it is using the actual password `{{ $user.password }}_PASSWORD` and thereby trying to reference an environment variable that is not defined.

**Comment by heytrav** [comment]
this appears to have been changed recently in #500

**Comment by heytrav** [comment]
Also confirm that using an earlier version of the helm chart (16.0.5) this doesn't occur

**Comment by mprimeaux** [comment]
A workaround that worked for me until the chart is patched was to define the `init:` stanza without the password for a user so at least the initial databases and users with permissions are correctly setup. For example:

```yaml
# Kubernetes Job which initializes multi-node CockroachDB cluster.
# It's not created if `statefulset.replicas` is `1`.
init:
  provisioning:
    enabled: true
    users:
      - name: db1user
        # NOTE: The following needs to be commented out for this defect.
        # password: foo
        options:
          [
            CONTROLJOB,
            CREATELOGIN,
            CREATEROLE,
            LOGIN,
            MODIFYCLUSTERSETTING,
            VIEWACTIVITY,
            VIEWCLUSTERSETTING,
            VIEWACTIVITYREDACTED,
            CREATEDB,
          ]
    databases:
      - name: db1
        options: [encoding='utf-8']
        owners: ["db1user", "root"]
        owners_with_grant_option: ["db1user", "root"]
```

Then I patched to allow username / password authentication for the `db1user` with a simple bash script. Here's an excerpt:

```shell
__namespace="default"
__password="w006KTBqVPsGmXiyk2V0WZcfnZyHs6p7dbdgM8sQRpGErl0z0rjDGgwZzVmWrpsU"

# Extract certs
kubectl get secret db-1-cockroachdb-client-secret --namespace "${__namespace}" -o jsonpath='{.data.tls\.crt}' | base64 -d > client.root.crt
kubectl get secret db-1-cockroachdb-client-secret --namespace "${__namespace}"s -o jsonpath='{.data.tls\.key}' | base64 -d > client.root.key

# Copy into the pod
kubectl cp client.root.crt chronicles/db-1-cockroachdb-0:/cockroach/cockroach-certs/client.root.crt
kubectl cp client.root.key chronicles/db-1-cockroachdb-0:/cockroach/cockroach-certs/client.root.key

# Now set the password
kubectl exec -it db-1-cockroachdb-0 ---namespace "${__namespace}" -- cockroach sql \
  --certs-dir=/cockroach/cockroach-certs \
  --host=localhost:26257 \
  --user=root \
  -e "ALTER USER db1user WITH PASSWORD '${__password}';"
```

Please note the above script assumes the Helm release name is `db-2` so you'll need to adjust that to match your release.

Anyway, we're at least no longer blocked for local development with this in place.
