### ISSUE TITLE
conf.single-node: true with tls.enabled: true fails due to host not matching certificate

### ISSUE THREAD

**Issue by JorritSalverda** [cockroachdb/helm-charts#57]
When using values

```yaml
conf:
  single-node: true

tls:
  enabled: true
```

The node starts up, performs the certificate request and after approving the csr starts up. However it then fails with:

```
Err: connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for localhost, cockroachdb-0.cockroachdb.default.svc.cluster.local, cockroachdb-0.cockroachdb, cockroachdb-public, cockroachdb-public.default.svc.cluster.local, not cockroachdb-0
```

It seems that the following flag should be passed on startup, but isn't for `conf.single-node: true`:

```
--advertise-host=$(hostname).${STATEFULSET_FQDN}
```

See https://github.com/cockroachdb/helm-charts/blob/master/cockroachdb/templates/statefulset.yaml#L195

Running cockroachdb chart `5.0.6`.

**Comment by JorritSalverda** [comment]
Passing the same arg through `statefulset.args` fixes the issue:

```yaml
statefulset:
  args:
  - '--advertise-host=$(hostname).${STATEFULSET_FQDN}'
```
