### ISSUE TITLE
Add ingress support

### ISSUE THREAD

**Issue by sergeyshaykhullin** [cockroachdb/helm-charts#6]
Add ingress helm chart support for cockroachdb web ui

```yaml
ingress:
  enabled: false
  annotations:
  hosts:
  - host:
    paths: []
  tls:
  - hosts: []
  secretName:
```
