### ISSUE TITLE
Add database and users provisioning support

### ISSUE THREAD

**Issue by sergeyshaykhullin** [cockroachdb/helm-charts#7]
Add database and users provisioning like:
- users: https://github.com/zalando/postgres-operator/blob/88735a798a8c9ef98897ac94efa09a14527de83b/manifests/complete-postgres-manifest.yaml#L13
- databases: https://github.com/zalando/postgres-operator/blob/88735a798a8c9ef98897ac94efa09a14527de83b/manifests/complete-postgres-manifest.yaml#L22

e.g.
```yaml
users:
- username: username
  password:

databases:
- name:
  owners: [username]
```

**Comment by sergeyshaykhullin** [comment]
@DuskEagle I want to start prototyping "provisioning" in a days

I my mind it will work as a post install helm hook, running job like init cluster, but running create if not exists statements. 

I don't think that values should be as complex as sql create constructions, so supports most used keywords for now

I can start with "raw sql" execution after cluster formation prototype

Any thoughts on this?

**Comment by Chili-Man** [comment]
This feature would be great; we're currently thinking about doing it as a Kubernetes Job that can be ran as a separate release and depending on a flag e.g. `--set job.bootstrap` . I think changing the password/permissions/deletion should be out of scope and the concern should only be on bootstrapping dbs /users - there's no need to manage the entire lifecycle of those resources from this helm chart

**Comment by keith-mcclellan** [comment]
I think we're more likely to do this in the operator rather than the helm chart.  We have an alpha operator available here: https://github.com/cockroachdb/cockroach-operator

**Comment by sergeyshaykhullin** [comment]
```yaml
users:
- username: username
  password:

databases:
- name:
  owners: [username]
  # https://www.cockroachlabs.com/docs/stable/manage-a-backup-schedule.html
  backup:
    into: s3://test/backups/test_schedule_1?AWS_ACCESS_KEY_ID=123&AWS_SECRET_ACCESS_KEY=123
    with: [revision_history]
    schedule: @daily
    options:
      first_run: now
```
