### ISSUE TITLE
Add prometheus operator ServiceMonitor support

### ISSUE THREAD

**Issue by sergeyshaykhullin** [cockroachdb/helm-charts#8]
```yaml
prometheus/metrics/monitoring/...:
  serviceMonitor:
    enabled: false
    interval: ...
    ...etc
```
